### ISSUE TITLE
iphone 6 and iphone 6 plus are not detect correct

### ISSUE THREAD

**Issue by eelcokoelewijn-afrogleap** [mozeal/UIDevice-HardwareName#3]
The hw.machine value for iphone 6 is 'iPhone7,2' and for iphone 6 plus 'iPhone7,1'.
It seems to be fixed in the head, but 6.0.0 tag is not on the head so the wrong values are returned for iphone 6 and iphone 6 plus.

Is it possible to add a new tag or put the 6.0.0 tag on the head of master?

**Comment by brightredchilli** [comment]
I'm also running into this issue. @mozeal, can you add a 6.1 or 6.0.1 tag at HEAD? I can submit an updated podspec to cocoapods but i need a tag to point at. this will prevent me from forking yet again this already really segmented(but useful) tool

**Comment by mozeal** [comment]
merged
